name: 학사일정 실행

on:
  workflow_dispatch: # 외부에서 신호를 받으면 실행됨

jobs:
  daily-briefing:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: 라이브러리 설치
        run: |
          pip install requests beautifulsoup4 pytz selenium webdriver-manager
      

      - name: 알림 보내기
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python calendar_bot.py
